server:
    port:7070
spring:
    datasource:
        hikari:
            driver-class-name: org.mariadb.jdbc.Driver
            jdbc-url:  jdbc:mariadb://localhost:3308/ashsilver_page?characterEncoding=UTF-8&serverTimezone=UTC
#            url: jdbc:mariadb://localhost:3308/ashsilver_page
            username: root
            password: abcd1234@
            connection-test-query: SELECT 1
    thymeleaf:
        enable: true
        prefix: classpath:/templates/
        suffix: .html
        cache: 'false'
        mode: HTML
        enabled: 'true'
        encoding: UTF-8

