server:
    port:7070
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3308/ashsilver_page
        username: root
        password: abcd1234@
    thymeleaf:
        enable: true
        prefix: classpath:/templates/
        suffix: .html
        cache: 'false'
        mode: HTML
        enabled: 'true'
        encoding: UTF-8